# Generated by Django 3.2rc1 on 2021-04-05 14:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("READY", "Ready"),
                            ("PROCESSING", "Processing"),
                            ("FAILED", "Failed"),
                            ("COMPLETE", "Complete"),
                        ],
                        db_index=True,
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("next_task", models.CharField(blank=True, max_length=100)),
                ("workspace", models.JSONField(null=True)),
                (
                    "queue_name",
                    models.CharField(db_index=True, default="default", max_length=20),
                ),
                ("priority", models.SmallIntegerField(db_index=True, default=0)),
            ],
            options={"ordering": ["-priority", "created"],},
        ),
    ]
