# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dbq', '0002_auto_20151016_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-priority', 'created']},
        ),
        migrations.AddField(
            model_name='job',
            name='priority',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
