# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dbq', '0003_auto_20180426_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='priority',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
