# Generated by Django 3.2rc1 on 2021-11-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_dbq", "0004_auto_20210818_0247"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="state",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("READY", "Ready"),
                    ("PROCESSING", "Processing"),
                    ("STOPPING", "Stopping"),
                    ("FAILED", "Failed"),
                    ("COMPLETE", "Complete"),
                ],
                db_index=True,
                default="NEW",
                max_length=20,
            ),
        ),
    ]
